development:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: webapp_development
  username: postgres
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>

test:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: webapp_test
  username: postgres
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>

production:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: <%= ENV.fetch("POSTGRES_DB") { "webapp_production" } %>
  username: postgres
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>
